/**
 * generateTestStub — Vitest file generator for authored rules.
 *
 * Design ref: sdd/authoring-dsl/design — Decision 4 (generateTestStub).
 *
 * PURE FUNCTION: accepts a RuleDoc, returns a valid Vitest source file as a string.
 * No IO — the string is WRITTEN to disk at the use-case/CLI layer, never by domain.
 *
 * Generated file structure mirrors bless.test.ts style:
 *   - File header comment: // PHB {source}: "{ruleText}"
 *   - // RED SENTINEL block (test fails before builder exists — strict TDD gate)
 *   - One describe() + it() per testCase entry
 *   - Each it() has // PHB {source} inline comment
 *   - Round-trip assertion: JSON.parse(JSON.stringify(instances))
 *   - Provenance assertion: breakdown contains expectedBreakdownSource label
 *
 * Author supplies:
 *   - rule.source (required), rule.ruleText (optional)
 *   - rule.testCases[].{params, expectedInstances, expectedResolution}
 *
 * Generator produces:
 *   - The entire .test.ts file: imports, ctx helper, register loop,
 *     structural + round-trip + provenance assertions, PHB comments
 */
import type { RuleDoc } from './types.js';

// ── Public API ────────────────────────────────────────────────────────────────

/**
 * Generate a Vitest test file stub for an authored rule.
 *
 * PURE: RuleDoc (string/object in) → file content string (string out). No IO.
 *
 * @param rule — validated RuleDoc (output of parseRule)
 * @returns string — the complete .test.ts file content
 */
export function generateTestStub(rule: RuleDoc): string {
  const { id, source, ruleText, testCases } = rule;

  // ── File header ────────────────────────────────────────────────────────────
  const lines: string[] = [];

  lines.push(`/**`);
  lines.push(` * Tests for ${id} — generated by generateTestStub.`);
  lines.push(` *`);
  if (ruleText != null) {
    lines.push(` * PHB ${source}: "${ruleText}"`);
  } else {
    lines.push(` * PHB ${source}`);
  }
  lines.push(` *`);
  lines.push(` * // RED SENTINEL — this file is generated BEFORE the builder exists.`);
  lines.push(` * // Vitest will fail to import the builder, making this file RED.`);
  lines.push(` * // Write the builder (${id}.ts) to turn this GREEN.`);
  lines.push(` */`);
  lines.push(`import { describe, it, expect } from 'vitest';`);
  lines.push(`// RED SENTINEL: import the rule builder (does not exist yet — RED)`);
  lines.push(`import { build${toPascalCase(id)} } from './${id}.js';`);
  lines.push(`import { createInMemoryRegistry } from '../registry/query.js';`);
  lines.push(`import { resolveStat } from '../resolve/stat.js';`);
  lines.push(`import type { EntityId } from '../types.js';`);
  lines.push(`import type { EvaluationContext } from '../context.js';`);
  lines.push(``);
  lines.push(`// ── Helpers ──────────────────────────────────────────────────────────────────`);
  lines.push(``);
  lines.push(`function eid(s: string): EntityId {`);
  lines.push(`  return s as EntityId;`);
  lines.push(`}`);
  lines.push(``);
  lines.push(`function makeCtx(selfId: EntityId): EvaluationContext {`);
  lines.push(`  return { self: { id: selfId, conditions: [] }, activeConditions: [] };`);
  lines.push(`}`);
  lines.push(``);

  // ── Test cases ─────────────────────────────────────────────────────────────
  if (testCases.length === 0) {
    lines.push(`// No test cases defined — add them to the rule's testCases array.`);
    lines.push(`describe('${id} — (no test cases)', () => {`);
    lines.push(`  it.todo('add test cases to the rule');`);
    lines.push(`});`);
  } else {
    for (let i = 0; i < testCases.length; i++) {
      const tc = testCases[i]!;
      const description = tc.description ?? `test case ${i + 1}`;
      const params = tc.params ?? {};
      const expectedResolution = tc.expectedResolution;

      lines.push(`// ── Test case ${i + 1}: ${description} ────────────────────────────────────────`);
      lines.push(``);
      lines.push(`describe('${id} — ${description}', () => {`);

      // ── Main assertion it() ────────────────────────────────────────────────
      lines.push(`  it('${description}', () => {`);
      if (ruleText != null) {
        lines.push(`    // ${source} — ${ruleText}`);
      } else {
        lines.push(`    // ${source}`);
      }
      lines.push(``);
      lines.push(`    const registry = createInMemoryRegistry();`);

      // Build params for the call
      const paramLines = buildParamLines(params);
      for (const line of paramLines) {
        lines.push(`    ${line}`);
      }

      lines.push(``);
      lines.push(`    const instances = build${toPascalCase(id)}(${buildParamArgs(params)});`);
      lines.push(`    instances.forEach((inst) => registry.register(inst));`);
      lines.push(``);

      // Structural assertion for each expectedInstance
      if (tc.expectedInstances.length > 0) {
        lines.push(`    // Structural: assert expected instances are registered`);
        lines.push(`    expect(instances).toHaveLength(${tc.expectedInstances.length});`);
        for (let j = 0; j < tc.expectedInstances.length; j++) {
          const expected = tc.expectedInstances[j];
          lines.push(`    expect(instances[${j}]).toMatchObject(${JSON.stringify(expected, null, 2).split('\n').join('\n    ')});`);
        }
        lines.push(``);
      }

      // Resolution assertion
      if (expectedResolution != null) {
        const { stat, base, expectedValue, expectedBreakdownSource } = expectedResolution;
        const ownerParam = resolveOwnerFromParams(params);
        lines.push(`    // Resolution: stat breakdown contains expected source`);
        lines.push(`    const ctx = makeCtx(eid('${ownerParam}'));`);
        lines.push(`    const result = resolveStat(eid('${ownerParam}'), '${stat}', ${base}, ctx, registry);`);
        lines.push(`    expect(result.value).toBe(${JSON.stringify(expectedValue)});`);
        lines.push(`    const src = result.breakdown.find((s) => s.label === '${expectedBreakdownSource}');`);
        lines.push(`    expect(src, 'expected source label in breakdown').toBeDefined();`);
        lines.push(``);
      }

      lines.push(`  });`);

      // ── Round-trip it() ────────────────────────────────────────────────────
      lines.push(``);
      lines.push(`  it('${description} — round-trip: instances survive JSON serialization', () => {`);
      lines.push(`    // PHB ${source}: round-trip (JSON.parse(JSON.stringify) must preserve instances)`);
      lines.push(``);
      lines.push(`    const registry = createInMemoryRegistry();`);
      for (const line of paramLines) {
        lines.push(`    ${line}`);
      }
      lines.push(``);
      lines.push(`    const instances = build${toPascalCase(id)}(${buildParamArgs(params)});`);
      lines.push(`    instances.forEach((inst) => registry.register(inst));`);
      lines.push(``);
      lines.push(`    // Serialize + reload into a fresh registry`);
      lines.push(`    const serialized = JSON.stringify(instances);`);
      lines.push(`    // JSON.parse(JSON.stringify(...)) round-trip must be lossless`);
      lines.push(`    const reloaded = JSON.parse(JSON.stringify(JSON.parse(serialized))) as typeof instances;`);
      lines.push(``);
      lines.push(`    const freshRegistry = createInMemoryRegistry();`);
      lines.push(`    reloaded.forEach((inst) => freshRegistry.register(inst));`);
      lines.push(``);
      lines.push(`    expect(reloaded).toHaveLength(instances.length);`);
      lines.push(`    for (let i = 0; i < instances.length; i++) {`);
      lines.push(`      expect(reloaded[i]).toMatchObject({ def: instances[i]!.def });`);
      lines.push(`    }`);
      lines.push(`  });`);

      lines.push(`});`);
      lines.push(``);
    }
  }

  return lines.join('\n');
}

// ── Helpers ───────────────────────────────────────────────────────────────────

/** Convert kebab-case to PascalCase for builder function names. */
function toPascalCase(id: string): string {
  return id
    .split('-')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

/** Generate const declarations from params record. */
function buildParamLines(params: Record<string, unknown>): string[] {
  const lines: string[] = [];
  for (const [key, value] of Object.entries(params)) {
    if (Array.isArray(value)) {
      const items = value.map((v) => `eid('${v}')`).join(', ');
      lines.push(`const ${key} = [${items}];`);
    } else if (typeof value === 'string') {
      lines.push(`const ${key} = eid('${value}');`);
    } else {
      lines.push(`const ${key} = ${JSON.stringify(value)};`);
    }
  }
  return lines;
}

/** Generate the argument list string for the builder call. */
function buildParamArgs(params: Record<string, unknown>): string {
  return Object.keys(params).join(', ');
}

/** Resolve the owner entity ID from params for makeCtx. Prefer 'owner', 'charId', 'casterId'. */
function resolveOwnerFromParams(params: Record<string, unknown>): string {
  const preferred = ['owner', 'charId', 'casterId'];
  for (const key of preferred) {
    if (key in params) {
      const v = params[key];
      return typeof v === 'string' ? v : String(v);
    }
  }
  // Fall back to first string param
  for (const value of Object.values(params)) {
    if (typeof value === 'string') return value;
  }
  return 'char-1';
}
